# Generated by Django 3.2.7 on 2021-10-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Name : ')),
                ('surname', models.TextField(verbose_name='Surname : ')),
                ('password', models.TextField(verbose_name='Password : ')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Login Date : ')),
                ('balance', models.IntegerField(verbose_name='Balance : ')),
            ],
        ),
    ]
